// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Footer from "@/components/Footer";
// import Header from "@/components/Header";
// import Announcement from "@/components/Announcement";
// import { CartProvider } from "@/context/CartContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//          <Announcement />
//         <Header />
//         <CartProvider>
//         {children}
//         </CartProvider>
//         <Footer />
//       </body>
//     </html>
//   );
// }


import type { Metadata, Viewport } from "next";
import TopBanner from "@/components/layout/Banner/TopBanner";
import TopNavbar from "@/components/layout/Navbar/TopNavbar/page";
import Footer from "@/components/layout/Footer/page";
import { ClerkProvider } from "@clerk/nextjs";
import Providers from "./provider";


export const metadata: Metadata = {
  title: "WardrobeWonder",
  description: "E-Commerce Website",
};

export const viewport: Viewport = {
  themeColor: "#000000",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      
        <body>
        
          <TopBanner />
          <Providers>
            <TopNavbar /> 
            {children}
          </Providers>
          <Footer />
        </body>
      </html></ClerkProvider>
  );
}
